services:
  - type: web
    name: telegramcoursebot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python course_bot.py
    plan: free
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: PORT
        value: 10000